### ISSUE TITLE
Error when texts get to long

### ISSUE THREAD

**Issue by slompf18** [pagedjs/pagedjs#104]
The page below leads to an error (Chrome). Remove the last number (7) and the error goes away.

Error:
```
paged.polyfill.js:1036 
       Uncaught (in promise) TypeError: node.getAttribute is not a function
    at findElement (paged.polyfill.js:1036:20)
    at Layout.createBreakToken (paged.polyfill.js:1668:21)
    at Layout.findBreakToken (paged.polyfill.js:1706:23)
    at Layout.renderTo (paged.polyfill.js:1448:27)
    at Page.layout (paged.polyfill.js:2163:47)
    at Chunker.layout (paged.polyfill.js:2918:29)
    at async Chunker.renderAsync (paged.polyfill.js:2839:17)
```

Code:
```
<html>
  <head>
    <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
  </head>
  <body>
    <h1>First Header</h1>
    <p>First content</p>
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
01234567890123456789012345678901234567890123456789
0123456789012345678901234567
  </body>
</html>
```

**Comment by mo** [comment]
I ran into the same bug as well:
```
<script src="paged.polyfill.js"></script>
<link href="interface.css" rel="stylesheet" type="text/css" />
<style>
@page {
  size: A4;
  margin: 0 0 0 0;
}
body {
    padding: 0;
    margin: 0;
}
pre {
    margin: 0;
}
</style>
<pre>
</pre>
<script>
const pre = document.querySelector("pre")
Array(100).fill().map((x,i) => `word ${i+1}`).forEach(word => pre.innerHTML += word + "\n")
</script>
```

**Comment by julientaq** [comment]
Hi tjere. So what happens here is that paged.js/chrome can’t find where to add a page break. There could be multiple reasons, but my feeling is that having no white space whatsoever just kill the thing, as it can’t find where to break.

To be honest, the browser will not know where to cut either if there is no white space: it will simple leave the long line of text without breaking lines. Which often happen with non realistic html (such as a long list of number without any white space, outside of any HTML tag). 

I’m adding this to the list of issues to look at. Did you got the same issue with more real world html / css? i’m curious to see if this extreme example is the problem or if there is something else behind.

**Comment by mo** [comment]
In slompf18's case it's probably just a really long word that causes it to call getAttribute() on a text node. In my case, maybe the same thing happens because of the PRE tag.

One curious thing I discovered when debugging this issue was that pagedjs can do pagination differently depending on whether you have chrome devtools open or not. This can be seen with this example that uses a sentence from your last reply @julientaq
https://martin.minimum.se/pagedjs-pre/

...if I have chrome devtools open the first page just contains the sentence once and then rest of the sentences end up on the second page (except for half of the sentence which is just deleted by pagedjs during pagination?). However, if I close devtools then pagedjs will instead just put everything in a single page (i.e. it doesn't even try to split the large PRE into two PRE elements).

This is what chrome looks like when the first part of the sentence disappears in the page break:
![image](https://user-images.githubusercontent.com/7117/201527975-03ffc8d0-e397-44d9-b058-5d536546692b.png)

**Comment by mo** [comment]
@julientaq thanks for working on this btw... I watched your talk from dpub summit 2019 earlier today while trying to understand paged.js internals better. :+1:

**Comment by julientaq** [comment]
Thanks for the kind words.

That’s interresting. as we got a similar problem on another book were working on.

I believe that the right space taken by the inspector  may affect the with calculations for the pages, (which are css columns until they’re are transformed into pages). 

@fchasen our main  dev should have a better understanding than me about his.

**Comment by carstenschwede** [comment]
I had a similar issue when `.textContent` was `\n\n\n`. It seems that at some point, pagedjs expects the previous sibling of a `textNode` to not be `textNode`. 

I then replaced

```javascript
if (isText(lastChild)) {
    if (lastChild.parentNode.dataset.ref) {
        lastNodeIndex = indexOf$3(lastChild);
        lastChild = lastChild.parentNode;
    } else {
        lastChild = lastChild.previousSibling;
    }
}
```

with

```javascript
while(lastChild && isText(lastChild)) {
    if (lastChild.parentNode.dataset.ref) {
        lastNodeIndex = indexOf$3(lastChild);
        lastChild = lastChild.parentNode;
    } else {
        lastChild = lastChild.previousSibling;
    }
    if (isText(lastChild) && lastChild.textContent.trim() !== "") {
        console.warn(lastChild,"has text which might be too long");
    }
}
```

which seems to have fixed it without noticeable errors.
