### ISSUE TITLE
Tailwind Typography 0.5.10 causes '[class~=not-prose] *)):before' is not a valid selector

### ISSUE THREAD

**Issue by Petercopter** [pagedjs/pagedjs#166]
We are using [Tailwind Typography](https://github.com/tailwindlabs/tailwindcss-typography) in conjunction with paged.js to generate PDFs. After upgrading to Typography `0.5.10`, we are getting this error:
```
paged.polyfill.js:30815 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'DocumentFragment': '[class~=not-prose] *)):before' is not a valid selector.
    at NthOfType.processSelectors (https://unpkg.com/pagedjs/dist/paged.polyfill.js:30815:27)
    at NthOfType.afterParsed (https://unpkg.com/pagedjs/dist/paged.polyfill.js:30809:9)
    at https://unpkg.com/pagedjs/dist/paged.polyfill.js:424:26
    at Array.forEach (<anonymous>)
    at Hook.trigger (https://unpkg.com/pagedjs/dist/paged.polyfill.js:423:15)
    at Chunker.flow (https://unpkg.com/pagedjs/dist/paged.polyfill.js:2916:33)
    at async Previewer.preview (https://unpkg.com/pagedjs/dist/paged.polyfill.js:33178:15)
    at async https://unpkg.com/pagedjs/dist/paged.polyfill.js:33240:11
```
I'm guessing this change may be the culprit:
> Remove typography styles from not-prose elements in addition to their children (https://github.com/tailwindlabs/tailwindcss-typography/pull/301)

I don't actually have a "working" example repo, because `0.5.10` is not on the Tailwind Play CDN yet, so I'm jumping the gun a little bit, but this code here will work once the new version is available:

```
<!DOCTYPE html>
<html>
<head>
  <script src="https://unpkg.com/pagedjs/dist/paged.polyfill.js"></script>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://cdn.tailwindcss.com?plugins=typography@0.5.10"></script>
</head>
<body>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec sit amet ultricies massa. Morbi tempor sodales
    hendrerit. Vestibulum at gravida est. Nulla ullamcorper purus vel mauris interdum scelerisque. Duis a vestibulum
    velit. Morbi luctus quam at mauris porta eleifend.</p>
</body>
</html>
```

**Comment by eread** [comment]
@fchasen Is this something easy to fix? I ran into this problem also, and originally raised the issue with a theme I use for a site: https://github.com/nunocoracao/blowfish/issues/1014.

There's more discussion at: https://github.com/tailwindlabs/tailwindcss-typography/issues/320.

**Comment by VissionNZ** [comment]
Haven't done any real digging myself so not too helpful, but can +1 this issue. 

Rolling back to tailwind-typography 0.5.9 makes the issue go away.

**Comment by jesse-a-reilly** [comment]
No such luck for me in downgrading to Tailwind Typography v0.5.9 - I still receive a `[class~=not-prose] *))` error:
`paged.polyfill.js:30037 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'DocumentFragment': ' th):not(:where([class~="not-prose"] *)))' is not a valid selector.`

**Comment by eread** [comment]
> No such luck for me in downgrading to Tailwind Typography v0.5.9 - I still receive a `[class~=not-prose] *))` error: `paged.polyfill.js:30037 Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'DocumentFragment': ' th):not(:where([class~="not-prose"] *)))' is not a valid selector.`

I could never solve this and ended up using a different tool: https://github.com/condorheroblog/html-export-pdf-cli#readme

**Comment by julientaq** [comment]
hi folks.

the way pagedjs work is by trying to rebuild the html and css trees to set the page system up in the browser.

We’re trying to get a system where those complex selector can still work (basically rewriting the `[class~=prose]` into a querySelector that would look for any element inside the content that would contain "prose" in its name.

mix that with the cascade, the negative selectors, and the selectors score system, and you can see the amount of complexity we dig in. Not even talking about performances here.

That said, it’s something we want to support in the long run. I wonder if we could manipulate some lighntingCSS features to rewrite the css with features that could be understandable by the querySelectors.

In the meantime, the process would be to look for a replacement of the rules you use that breaks paged.js (and if you would be so kind to write them here, that would be great!).

**Comment by jesse-a-reilly** [comment]
Thanks @julientaq. After spending a few weeks delving into CSS for print, I can appreciate the complexities that paged.js is working with! If I find some replacement rules for Tailwind's typography plugin, I'll include them here.

@eread I checked out https://github.com/condorheroblog/html-export-pdf-cli. While it has some options for header and footer content, it's still using Puppeteer under the hood, so I'm guessing it will be limited when it comes to using the full CSS paged media and generated content specs.

**Comment by eread** [comment]
> hi folks.
> 
> the way pagedjs work is by trying to rebuild the html and css trees to set the page system up in the browser.
> 
> We’re trying to get a system where those complex selector can still work (basically rewriting the `[class~=prose]` into a querySelector that would look for any element inside the content that would contain "prose" in its name.
> 
> mix that with the cascade, the negative selectors, and the selectors score system, and you can see the amount of complexity we dig in. Not even talking about performances here.
> 
> That said, it’s something we want to support in the long run. I wonder if we could manipulate some lighntingCSS features to rewrite the css with features that could be understandable by the querySelectors.
> 
> In the meantime, the process would be to look for a replacement of the rules you use that breaks paged.js (and if you would be so kind to write them here, that would be great!).

Thanks for getting back to us, @julientaq. I put as much detail as I could in: https://github.com/nunocoracao/blowfish/issues/1014, including the commits in that project that caused me problems with this project.

**Comment by Samuel-Webster** [comment]
For what it's worth @julientaq these are the tailwind selectors that appear to be causing problems for us:
- `[class~=not-prose] *)):before`
- `[class~=not-prose] *))`

We have gotten around it by just skipping those selectors in the two `processSelectors()` functions on `paged.polyfil.js`, I know this is very, very hacky, but for anyone else who needs a workaround, this is what we have done and for our use case, it seems to be working fine.

```js
processSelectors(parsed, selectors) {
    // add the new attributes to matching elements
    for (let s in selectors) {

        // Temp patch
        try {
            parsed.querySelectorAll(s);
        } catch (error) {
            console.warn('The following selector is not compatable with Paged.js: ' + s);
            return;
        }
```

**Comment by julientaq** [comment]
oh thanks a lot for sharing your solution @Samuel-Webster. 

It’s weird because the `[class~=not-prose] *` should work and the `before` pseudo should be taken into account. 

🤔 i’ll add it to the list of things to check.

**Comment by Petercopter** [comment]
I tested against `pagedjs@0.5.0-beta.1` and this seems to be resolved.

**Comment by bumbummen99** [comment]
I am on v0.5.0-beta.2

I do get the following error when i use the built version of Tailwind v4 - it does work just fine when using the Vite development server:
`SyntaxError: Failed to execute 'querySelectorAll' on 'DocumentFragment': '[class~=not-prose] *)):before' is not a valid selector.`

It seems like [Handler.processSelectors](https://github.com/pagedjs/pagedjs/blob/f364d95adab074ed5b44ca5b5383e61648b8ade2/src/modules/paged-media/nth-of-type.js#L41) gets the selectors parameter in a weirdly split way.
```
".prose :where(blockquote p:first-of-type):not(:where([class~=not-prose]": (2) […]
".prose :where(blockquote p:last-of-type):not(:where([class~=not-prose]": (2) […]
"[class~=not-prose] *)):after": (2) […]
"[class~=not-prose] *)):before": (2) […]
```

This is the related CSS 
```
.prose :where(blockquote p:first-of-type):not(:where([class~="not-prose"],[class~="not-prose"] *))::before {
  content: open-quote;
}

.prose :where(blockquote p:last-of-type):not(:where([class~="not-prose"],[class~="not-prose"] *))::after {
  content: close-quote;
}
```

@julientaq Is this something you have already been working on?
