### ISSUE TITLE
pagedjs timeout when trying to create PDF with puppeteer in Docker container

### ISSUE THREAD

**Issue by nbyloff** [pagedjs/pagedjs#230]
I am having a Timeout issue when trying to generate a PDF in a docker container. I have setup a test environment here: https://github.com/nbyloff/puppeteer-issue

To recreate the issue, checkout the above project and follow these steps

````
# build image with puppeteer and necessary libaries
$ docker build --build-arg UID=$(id -u) --platform=linux/amd64 -t bugs_node .

# start project
$ docker-compose up -d

# login to container
$ docker-compose exec app sh

# inside container
$ node demo.js
````

Follow the above commands will result in this error:
````
$ node demo.js
200 http://demo.test:8080/demo.html
302 https://unpkg.com/pagedjs/dist/paged.polyfill.js
200 https://unpkg.com/pagedjs@0.4.3/dist/paged.polyfill.js
file:///home/web/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:56
            this.#timeoutError = new TimeoutError(opts.message);
                                 ^

TimeoutError: Navigation timeout of 30000 ms exceeded
    at new Deferred (file:///home/web/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:56:34)
    at Deferred.create (file:///home/web/node_modules/puppeteer-core/lib/esm/puppeteer/util/Deferred.js:18:16)
    at new LifecycleWatcher (file:///home/web/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/LifecycleWatcher.js:66:46)
    at CdpFrame.goto (file:///home/web/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/Frame.js:148:29)
    at CdpFrame.<anonymous> (file:///home/web/node_modules/puppeteer-core/lib/esm/puppeteer/util/decorators.js:94:27)
    at CdpPage.goto (file:///home/web/node_modules/puppeteer-core/lib/esm/puppeteer/api/Page.js:561:43)
    at main (file:///home/web/demo.js:29:16)


````

However, if I remove `https://unpkg.com/pagedjs/dist/paged.polyfill.js` reference, the puppeteer process works flawlessly. So something with pagedjs is timing out, but I don't know where or how to troubleshoot this issue. What could be causing pagedjs to hang like this?

Once you start the docker project, the HTML demo file is viewable here: http://demo.test:8080/demo.html

**Comment by NigelCunningham** [comment]
Hi Nathan.

Thanks for your report. 

If you visit the pager puppeteer is visiting, you should be able to check for JS errors or other issues and check the results of the pagination process. In my Drupal pdf_api module, you'll also find a js file (wait for js iirc) that might be useful in ensuring other code waits long enough for the pagination to complete. 

Regards, 

Nij

**Comment by nbyloff** [comment]
Hi @NigelCunningham I have checked the page manually and it loads immediately with no JS errors. This demo only has 3 pages in it to ensure it was quick, but I have up'd the timeout to several minutes and it still never completes.

I edited my post above after you commented, but I have this handler in my demo:

````
class handlers extends Paged.Handler {
        constructor(chunker, polisher, caller) {
            super(chunker, polisher, caller);
        }

        beforeParsed(content) {
            createToc({
                content: content,
                tocElement: '#my-toc-content',
                titleElements: ['.manual-payload h1.chapter-title']
            });
            console.log('completed toc');
        }

        afterRendered(pages) {
            console.log('afterRendered called');
            window.report = 'ready'; // var for PDF generation to monitor so we know when to save PDF
            console.log(window.report);
        }

    }
    Paged.registerHandlers(handlers);
````

It draws the TOC immediately, but the `afterRendered` method is never called. In running my docker demo, you can see the console.log from `beforeParsed` called, but not in `afterRendered`.

**Comment by NigelCunningham** [comment]
Hmm, it definitely shouldn't take anything like 30s to run so I guess something is just dying or not getting called. I'll see if I can find some time to look into this but can't make any real promises sorry.

**Comment by nbyloff** [comment]
> Hmm, it definitely shouldn't take anything like 30s to run so I guess something is just dying or not getting called. I'll see if I can find some time to look into this but can't make any real promises sorry.

Thanks for any help you may be able to give. I am going to try adding console log throughout the code between `afterParsed` & `beforePageLayout` events and see if it narrows down what's dying.

**Comment by nbyloff** [comment]
Hi @NigelCunningham a quick follow up. I have tracked down that it's hanging on generating a `UUID` in this method, it never finishes:

````
/**
	 * Generates a UUID
	 * based on: http://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid-in-javascript
	 * @returns {string} uuid
	 */
function UUID() {
		var d = new Date().getTime();
		if (typeof performance !== "undefined" && typeof performance.now === "function") {
			d += performance.now(); //use high-precision timer if available
		}
		return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function (c) {
			var r = (d + Math.random() * 16) % 16 | 0;
			d = Math.floor(d / 16);
			return (c === "x" ? r : (r & 0x3 | 0x8)).toString(16);
		});
	}
````

When I change this function to just return a random number, my entire script finishes as expected. Going to spend some time tomorrow trying to find out why but wanted to share in case you have thoughts. 

The stackoverflow thread in the function comments mentions [crypto.randomUUID](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID). I tried to use that function instead but got the error `crypto.randomUUID is not a function`. But it does say that only works over localhost or HTTPS which is probably why this library doesn't use it.

I'll post back if I find a solution.

**Comment by nbyloff** [comment]
The stackoverflow thread referenced in the function comments had an updated UUID function, when I change it to this... it works perfectly!

````
return "10000000-1000-4000-8000-100000000000".replace(/[018]/g, c =>
    (+c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> +c / 4).toString(16)
  );
````

Any thoughts on what the different might be? And if this method works just as well if not better? Worst case scenario is I have to self-host pagedjs library to replace this UUID function, but would love to see it updated to use this function if possible.

**Comment by NigelCunningham** [comment]
Hmm, I've never touched that function so at least I didn't break it :)

I'll happily defer to Fred or Julian here but my understanding is that the UUIDs are essentially an optimisation, allowing us to quickly look up different parts of the DOM as we work. As long as the function doesn't produce duplicates, I can't see that we'd care too much about a change that prevented hangs. Might be helpful to understand better what the cause of the hang is, though.

**Comment by nbyloff** [comment]
> Hmm, I've never touched that function so at least I didn't break it :)
> 
> I'll happily defer to Fred or Julian here but my understanding is that the UUIDs are essentially an optimisation, allowing us to quickly look up different parts of the DOM as we work. As long as the function doesn't produce duplicates, I can't see that we'd care too much about a change that prevented hangs. Might be helpful to understand better what the cause of the hang is, though.

I am asking around if anyone knows the difference between the two UUID functions, but it's beyond me. Tagging @fchasen @julientaq to see if they have issue with updating the UUID function. The current function uses `Math.random()`, which is not recommended in the original SO thread here, which could be another reason to update it. 

http://stackoverflow.com/questions/105034/how-to-create-a-guid-uuid-in-javascript

**Comment by cdelacombaz** [comment]
@nbyloff many thanks for finding and sharing this!

I was working with pagedjs and puppeteer without docker first and everything worked fine. As per project requirements, the app needed to be dockerized and it just stopped working, hanging without error message and resulting in timeouts.

I forked the pagedjs package, updated the UUID function as you mentionend and now it works :)

Would be great if this could be fixed in this library. pagedjs is the first library I found where creating PDF is fun! 

@NigelCunningham @fchasen @julientaq :  if you confirm that the code can be update as suggested by @nbyloff, I'm happy to create a PR.

**Comment by nbyloff** [comment]
@cdelacombaz thank you for the confirmation, glad it fixed your issue as well. I do have a PR ready I just haven't committed it yet to this repo. @NigelCunningham was hoping to get understanding on why this issue happens in the first place. I tried to get help on SO but the question got closed because it took too much code to replicate (HTML, puppeteer JS, docker image, etc). It hangs in a promise that never returns, but that's all I know. I have just built it into my local build and moved on since I couldn't find anyone else to confirm the issue.

But since you can confirm it fixes your docker issue as well, I think I will push a PR today. [According to SO](https://stackoverflow.com/a/2117523/239375), it would also make it compliant with RFC4122 UUIDs.

**Comment by julientaq** [comment]
i let @fchasen answer that one. Please be patient, he’s under lot of stuff these days :D
