### ISSUE TITLE
script throws an error and stops working (using latest commit)

### ISSUE THREAD

**Issue by bakkot** [pagedjs/pagedjs#238]
Here's a repro, where `"./paged.polyfill.js"` is what you get building this repo as of https://github.com/pagedjs/pagedjs/commit/4cbe30119751cb73d0599b7377f0d8423f2307de. 

<details>
<summary>repro</summary>

```html
<!doctype html>
<html lang="en-us">
<meta charset="UTF-8">
<title>Poems</title>
<script src="./paged.polyfill.js"></script>

<style>
body {
  font-family: Baskerville;
}

@page {
  size: 4.25in 6.875in;
  margin-top: .7in;
  margin-bottom: .58in;
  padding: 0;

  font-size: 9pt;
  @bottom-center {
    content: counter(page);
  }
}

@page:left {
  margin-left: .4in;
  margin-right: .6in;
}

@page:right {
  margin-left: .6in;
  margin-right: .45in;
}

.title-block {
  text-align: center;
  margin-bottom: .3in;
  font-weight: 300;
  line-height: 1;
}

.title {
  font-size: 14pt;
  margin-bottom: 0.1in;
}

.author {
  font-size: 11pt;
}

.poem {
  page-break-after: always;
  font-size: 11pt;
}

.stanza {
  margin-bottom: 1.5em;
}

.line {
  line-height: 1.4em;
}

</style>
<body>

<section id="main">

<div class="title-block">
<div class="title">Break of Day</div>
<div class="author">John Donne</div>
</div>

<div class="poem"><div class="stanza"><div class="line"></div>
<div class="line">‘Tis true, ‘tis day, what though it be?</div>
<div class="line">O wilt thou therefore rise from me?</div>
<div class="line">Why should we rise because ‘tis light?</div>
<div class="line">Did we lie down because ‘twas night?</div>
<div class="line">Love, which in spite of darkness brought us hither,</div>
<div class="line">Should in despite of light keep us together.</div></div>
<div class="stanza"><div class="line">Light hath no tongue, but is all eye;</div>
<div class="line">If it could speak as well as spy,</div>
<div class="line">This were the worst that it could say,</div>
<div class="line">That being well I fain would stay,</div>
<div class="line">And that I loved my heart and honour so,</div>
<div class="line">That I would not from him, that had them, go.</div></div>
<div class="stanza"><div class="line">Must business thee from hence remove?</div>
<div class="line">Oh, that’s the worst disease of love,</div>
<div class="line">The poor, the foul, the false, love can</div>
<div class="line">Admit, but not the busied man.</div>
<div class="line">He which hath business, and makes love, doth do</div>
<div class="line">Such wrong, as when a married man doth woo.</div>
<div class="line"></div></div></div>



<div class="title-block">
<div class="title">Other Lives and Dimensions and Finally a Love Poem</div>
<div class="author">Bob Hicok</div>
</div>

<div class="poem"><div class="stanza"><div class="line"></div>
<div class="line">My left hand will live longer than my right. The rivers</div>
<div class="line">&nbsp;&nbsp;of my palms tell me so.</div>
<div class="line">Never argue with rivers. Never expect your lives to finish</div>
<div class="line">&nbsp;&nbsp;at the same time. I think</div></div>
<div class="stanza"><div class="line">praying, I think clapping is how hands mourn. I think</div>
<div class="line">&nbsp;&nbsp;staying up and waiting</div>
<div class="line">for paintings to sigh is science. In another dimension this</div>
<div class="line">&nbsp;&nbsp;is exactly what’s happening,</div></div>
<div class="stanza"><div class="line">it’s what they write grants about: the chromodynamics</div>
<div class="line">&nbsp;&nbsp;of mournful Whistlers,</div>
<div class="line">the audible sorrow and beta decay of “Old Battersea Bridge.”</div>
<div class="line">&nbsp;&nbsp;I like the idea of different</div></div>
<div class="stanza"><div class="line">theres and elsewheres, an Idaho known for bluegrass,</div>
<div class="line">&nbsp;&nbsp;a Bronx where people talk</div>
<div class="line">like violets smell. Perhaps I am somewhere patient, somehow</div>
<div class="line">&nbsp;&nbsp;kind, perhaps in the nook</div></div>
<div class="stanza"><div class="line">of a cousin universe I’ve never defiled or betrayed</div>
<div class="line">&nbsp;&nbsp;anyone. Here I have</div>
<div class="line">two hands and they are vanishing, the hollow of your back</div>
<div class="line">&nbsp;&nbsp;to rest my cheek against,</div></div>
<div class="stanza"><div class="line">your voice and little else but my assiduous fear to cherish.</div>
<div class="line">&nbsp;&nbsp;My hands are webbed</div>
<div class="line">like the wind-torn work of a spider, like they squeezed</div>
<div class="line">&nbsp;&nbsp;something in the womb</div></div>
<div class="stanza"><div class="line">but couldn’t hang on. One of those other worlds</div>
<div class="line">&nbsp;&nbsp;or a life I felt</div>
<div class="line">passing through mine, or the ocean inside my mother’s belly</div>
<div class="line">&nbsp;&nbsp;she had to scream out.</div></div>

<div class="stanza"><div class="line">Here when I say “I never want to be without you,”</div>
<div class="line">&nbsp;&nbsp;somewhere else I am saying</div>
<div class="line">“I never want to be without you again.” And when I touch you</div>
<div class="line">&nbsp;&nbsp;in each of the places we meet</div></div>
<div class="stanza"><div class="line">in all of the lives we are, it’s with hands that are dying</div>
<div class="line">&nbsp;&nbsp;and resurrected.</div>
<div class="line">When I don’t touch you it’s a mistake in any life,</div>
<div class="line">&nbsp;&nbsp;in each place and forever.</div>
<div class="line"></div></div></div>
```
</details>

This gives
```
paged.polyfill.js:1945 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'childNodes')
    at Layout.addOverflowNodes (paged.polyfill.js:1945:22)
    at paged.polyfill.js:1993:10
    at Array.forEach (<anonymous>)
    at Layout.addOverflowToPage (paged.polyfill.js:1981:24)
    at Layout.renderTo (paged.polyfill.js:1776:9)
    at Page.layout (paged.polyfill.js:3339:47)
    at Chunker.layout (paged.polyfill.js:4214:29)
    at async Chunker.renderAsync (paged.polyfill.js:4102:17)
```

It looks like it's assuming that `overflow` nodes always have a `.content`, but in fact that property is [only created conditionally](https://github.com/pagedjs/pagedjs/blob/4cbe30119751cb73d0599b7377f0d8423f2307de/src/chunker/layout.js#L621-L624).

**Comment by yslflow** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
