### ISSUE TITLE
Supported NodeJS version for paged-js-cli?

### ISSUE THREAD

**Issue by zopyx** [pagedjs/pagedjs#3]
The dependencies for NodeJS are possibly not properly documented.
At least NodeJS 13.9 throws this error

```
bin/pagedjs-cli 
internal/validators.js:118
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:118:11)
    at Object.resolve (path.js:980:7)
    at Object.<anonymous> (/home/ajung/src/pagedjs-cli/lib/node_modules/pagedjs-cli/bin/paged:55:23)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
(pagedjs-cli)ajung@zopyx-nuc ~/src/pagedjs-cli (master) $ bin/npm --version
6.13.7
(pagedjs-cli)ajung@zopyx-nuc ~/src/pagedjs-cli (master) $ bin/nodejs --version
v13.9.0
```

**Comment by zopyx** [comment]
Possibly unrelated to the NodeJS version since this occurs with NodeJS 12.5.0 as well

**Comment by julientaq** [comment]
The CLI runs on OSX running `node 11.15.0` and `node 13.9.0` on my computer. There is something else happening here.

It seems that you got an issue with the `path` argument.  

How do you try to run `pagedjs-cli`?

**Comment by julientaq** [comment]
I manage to recreate the issue you had: 

you need to open the terminal in the folder that contains your html file (which include links to your css) and hit `pagedjs-cli file.html` 

This sould be enough to get you started.
