### ISSUE TITLE
DOMException: Failed to execute 'querySelectorAll' on 'DocumentFragment': 'event)"]' is not a valid selector

### ISSUE THREAD

**Issue by ishanuda** [pagedjs/pagedjs#38]
Hi,
I see the following error when loading paged.polyfill with an html  page.
Tested even with a simple p tag adding text and the result is the same.

```
Uncaught (in promise) DOMException: Failed to execute 'querySelectorAll' on 'DocumentFragment': 'event)"]' is not a valid selector.
    at DocumentFragment.querySelectorAll (<anonymous>)
    at Following.processSelectors (http://127.0.0.1:5500/js/paged.polyfill-0.1.43.js:29454:27)
    at Following.afterParsed (http://127.0.0.1:5500/js/paged.polyfill-0.1.43.js:29448:9)
    at http://127.0.0.1:5500/js/paged.polyfill-0.1.43.js:364:26
    at Array.forEach (<anonymous>)
    at Hook.trigger (http://127.0.0.1:5500/js/paged.polyfill-0.1.43.js:363:15)
    at Chunker.flow (http://127.0.0.1:5500/js/paged.polyfill-0.1.43.js:2583:33)
    at async Previewer.preview (http://127.0.0.1:5500/js/paged.polyfill-0.1.43.js:31035:15)
    at async http://127.0.0.1:5500/js/paged.polyfill-0.1.43.js:31096:11

```

paged.polyfill library versions produces the problem:

v 0.1.42
v 0.1.43

NOTE: loading with v0.1.41 was fine and rendered the HTML page.
Did not check further down versions because the 0.1.41 was working fine.

regards.

**Comment by ishanuda** [comment]
Closing the issue as this is referred to in the GitLab repo.

[Please refer to the GitLab issue #275](https://gitlab.pagedmedia.org/tools/pagedjs/issues/275)
