### ISSUE TITLE
Error: Failed to launch the browser process

### ISSUE THREAD

**Issue by JaapJoris** [pagedjs/pagedjs#41]
When I run the `paged` CLI tool on Debian Bullseye, I get the following error:

```
$ node_modules/pagedjs-cli/bin/paged test.html -o test.pdf
◴ Loading: test.html(node:1555110) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
[0311/125006.784336:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
#0 0x5626745ebb39 base::debug::CollectStackTrace()
#1 0x56267455e4c3 base::debug::StackTrace::StackTrace()
#2 0x56267456ec80 logging::LogMessage::~LogMessage()
#3 0x562673000f5e content::ZygoteHostImpl::Init()
#4 0x562674508cf8 content::ContentMainRunnerImpl::Initialize()
#5 0x562674506e0b content::RunContentProcess()
#6 0x562674506f5c content::ContentMain()
#7 0x5626745583d2 headless::(anonymous namespace)::RunContentMain()
#8 0x5626745580bc headless::HeadlessShellMain()
#9 0x562671b59a03 ChromeMain
#10 0x7faab4b0ed0a __libc_start_main
#11 0x562671b5982a _start

Received signal 6
#0 0x5626745ebb39 base::debug::CollectStackTrace()
#1 0x56267455e4c3 base::debug::StackTrace::StackTrace()
#2 0x5626745eb6db base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7faab64ab140 (/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+0x1413f)
#4 0x7faab4b23ce1 gsignal
#5 0x7faab4b0d537 abort
#6 0x5626745ea665 base::debug::BreakDebugger()
#7 0x56267456f0f2 logging::LogMessage::~LogMessage()
#8 0x562673000f5e content::ZygoteHostImpl::Init()
#9 0x562674508cf8 content::ContentMainRunnerImpl::Initialize()
#10 0x562674506e0b content::RunContentProcess()
#11 0x562674506f5c content::ContentMain()
#12 0x5626745583d2 headless::(anonymous namespace)::RunContentMain()
#13 0x5626745580bc headless::HeadlessShellMain()
#14 0x562671b59a03 ChromeMain
#15 0x7faab4b0ed0a __libc_start_main
#16 0x562671b5982a _start
  r8: 0000000000000000  r9: 00007ffced0ad400 r10: 0000000000000008 r11: 0000000000000246
 r12: 00007ffced0ae710 r13: aaaaaaaaaaaaaaaa r14: 00007ffced0ae720 r15: 00007ffced0adea0
  di: 0000000000000002  si: 00007ffced0ad400  bp: 00007ffced0ad650  bx: 00007faab3458d80
  dx: 0000000000000000  ax: 0000000000000000  cx: 00007faab4b23ce1  sp: 00007ffced0ad400
  ip: 00007faab4b23ce1 efl: 0000000000000246 cgf: 002b000000000033 erf: 0000000000000000
 trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/opt/babeldat/backend/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)
    at Interface.<anonymous> (/opt/babeldat/backend/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)
    at Interface.emit (events.js:326:22)
    at Interface.close (readline.js:416:8)
    at Socket.onend (readline.js:194:10)
    at Socket.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1555110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1555110) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I only encounter this problem on this particular machine. The kernel it's running is up-to-date (Linux 5.9.0), so the message `No usable sandbox! Update your kernel` seems incorrect. Nevertheless, I tried appending the `--no-sandbox` argument but then I got this error:

```
$ node_modules/pagedjs-cli/bin/paged test.html -o test.pdf --no-sandbox
error: unknown option '--no-sandbox'
```

What could be the cause of this problem?

**Comment by julientaq** [comment]
The CLI part is to @fchasen to answer. He’s in pacific time, so it’s early morning for him. :)

**Comment by JaapJoris** [comment]
Solved! I ran the following command, as recommended [here](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#setting-up-chrome-linux-sandbox):

```
$ sudo sysctl -w kernel.unprivileged_userns_clone=1
```

And the error disappeared. Sorry for bothering you guys, and keep up the good work!

**Comment by julientaq** [comment]
You didn’t bothered at all!
it’s pretty useful to have solutions to issues we didnt get :)
Thanks for sharing the solution
