### ISSUE TITLE
Failed to execute 'querySelectorAll' on 'Element' when layout.

### ISSUE THREAD

**Issue by lxmfly123** [pagedjs/pagedjs#81]
Error

```
vendor.df3e6698.js:formatted:8828 DOMException: Failed to execute 'querySelectorAll' on 'Element': '.page-no:after:not([data-target-counter-5d7cd501-c917-4e41-87e9-781589bd8d4c])' is not a valid selector.
    at http://example.com/js/vendor.df3e6698.js:42:489189
    at Array.forEach (<anonymous>)
    at Wv.afterPageLayout (http://example.com/js/vendor.df3e6698.js:42:489101)
    at http://example.com/js/vendor.df3e6698.js:42:10974
    at Array.forEach (<anonymous>)
    at Oe.trigger (http://example.com/js/vendor.df3e6698.js:42:10945)
    at Pe.layout (http://example.com/js/vendor.df3e6698.js:42:30980)
    at async Pe.renderAsync (http://example.com/js/vendor.df3e6698.js:42:29917)
```

The css selector is a invalid selctor.

**Comment by julientaq** [comment]
hi @lxmfly123 
would you mind explaining a bit more what you’re tyring to do and sharing a bit of html and css?
otherwise it’s not really easy to help :)
thanks

**Comment by lxmfly123** [comment]
This issue turns out to be a problem with my scss compiler. It compiles `::after` to `:after`, which makes target counter fail to get the actual element selector.

https://github.com/pagedjs/pagedjs/blob/b756e3105e31ee59e1e29dedf0117e42f97dc834/src/modules/generated-content/target-counters.js#L81

btw, pagedjs is a very impressive work, i've been a sustaining donator.

**Comment by julientaq** [comment]
Aw thanks for the kind words (and the rest :D)!

There has been some fixes on the double colons normaly. `::after` or `:after`  should both work with 0.3.2. I’ll check that out to be sure.

Thanks again!

**Comment by lxmfly123** [comment]
yeah, i'm now using 0.2.0. The new regex in 0.3.2 is compatible with `:` and `::`.
